//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.28 at 11:06:19 AM WESZ 
//


package net.sf.ahtutils.xml.access;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ahtutils.aht-group.com/access}usecaseCategory" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ahtutils.aht-group.com/access}projectRoleCategory" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ahtutils.aht-group.com/access}roleCategory" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://ahtutils.aht-group.com/access}roleAutoAssign" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usecaseCategory",
    "projectRoleCategory",
    "roleCategory",
    "roleAutoAssign"
})
@XmlRootElement(name = "aclContainer")
public class AclContainer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected List<UsecaseCategory> usecaseCategory;
    @XmlElement(required = true)
    protected List<ProjectRoleCategory> projectRoleCategory;
    @XmlElement(required = true)
    protected List<RoleCategory> roleCategory;
    @XmlElement(required = true)
    protected List<RoleAutoAssign> roleAutoAssign;

    /**
     * Gets the value of the usecaseCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usecaseCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsecaseCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UsecaseCategory }
     * 
     * 
     */
    public List<UsecaseCategory> getUsecaseCategory() {
        if (usecaseCategory == null) {
            usecaseCategory = new ArrayList<UsecaseCategory>();
        }
        return this.usecaseCategory;
    }

    public boolean isSetUsecaseCategory() {
        return ((this.usecaseCategory!= null)&&(!this.usecaseCategory.isEmpty()));
    }

    public void unsetUsecaseCategory() {
        this.usecaseCategory = null;
    }

    /**
     * Gets the value of the projectRoleCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectRoleCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectRoleCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectRoleCategory }
     * 
     * 
     */
    public List<ProjectRoleCategory> getProjectRoleCategory() {
        if (projectRoleCategory == null) {
            projectRoleCategory = new ArrayList<ProjectRoleCategory>();
        }
        return this.projectRoleCategory;
    }

    public boolean isSetProjectRoleCategory() {
        return ((this.projectRoleCategory!= null)&&(!this.projectRoleCategory.isEmpty()));
    }

    public void unsetProjectRoleCategory() {
        this.projectRoleCategory = null;
    }

    /**
     * Gets the value of the roleCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleCategory }
     * 
     * 
     */
    public List<RoleCategory> getRoleCategory() {
        if (roleCategory == null) {
            roleCategory = new ArrayList<RoleCategory>();
        }
        return this.roleCategory;
    }

    public boolean isSetRoleCategory() {
        return ((this.roleCategory!= null)&&(!this.roleCategory.isEmpty()));
    }

    public void unsetRoleCategory() {
        this.roleCategory = null;
    }

    /**
     * Gets the value of the roleAutoAssign property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleAutoAssign property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleAutoAssign().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleAutoAssign }
     * 
     * 
     */
    public List<RoleAutoAssign> getRoleAutoAssign() {
        if (roleAutoAssign == null) {
            roleAutoAssign = new ArrayList<RoleAutoAssign>();
        }
        return this.roleAutoAssign;
    }

    public boolean isSetRoleAutoAssign() {
        return ((this.roleAutoAssign!= null)&&(!this.roleAutoAssign.isEmpty()));
    }

    public void unsetRoleAutoAssign() {
        this.roleAutoAssign = null;
    }

}
