//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.07 at 10:41:29 AM MEZ 
//


package net.sf.ahtutils.xml.access;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sf.ahtutils.xml.access package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sf.ahtutils.xml.access
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoleAutoAssign }
     * 
     */
    public RoleAutoAssign createRoleAutoAssign() {
        return new RoleAutoAssign();
    }

    /**
     * Create an instance of {@link ProjectRole }
     * 
     */
    public ProjectRole createProjectRole() {
        return new ProjectRole();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Usecases }
     * 
     */
    public Usecases createUsecases() {
        return new Usecases();
    }

    /**
     * Create an instance of {@link Usecase }
     * 
     */
    public Usecase createUsecase() {
        return new Usecase();
    }

    /**
     * Create an instance of {@link ProjectRoles }
     * 
     */
    public ProjectRoles createProjectRoles() {
        return new ProjectRoles();
    }

    /**
     * Create an instance of {@link AclQuery }
     * 
     */
    public AclQuery createAclQuery() {
        return new AclQuery();
    }

    /**
     * Create an instance of {@link UsecaseCategory }
     * 
     */
    public UsecaseCategory createUsecaseCategory() {
        return new UsecaseCategory();
    }

    /**
     * Create an instance of {@link AclContainer }
     * 
     */
    public AclContainer createAclContainer() {
        return new AclContainer();
    }

    /**
     * Create an instance of {@link RoleAutoAssign.Add }
     * 
     */
    public RoleAutoAssign.Add createRoleAutoAssignAdd() {
        return new RoleAutoAssign.Add();
    }

    /**
     * Create an instance of {@link RoleAutoAssign.Rm }
     * 
     */
    public RoleAutoAssign.Rm createRoleAutoAssignRm() {
        return new RoleAutoAssign.Rm();
    }

    /**
     * Create an instance of {@link Access }
     * 
     */
    public Access createAccess() {
        return new Access();
    }

}
