//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 09:19:55 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ahtutils.aht-group.com/security")
package net.sf.ahtutils.xml.security;
