//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.07 at 10:39:33 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ahtutils.aht-group.com/utils", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sf.ahtutils.xml.utils;
