//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.01 at 07:39:45 AM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ahtutils.aht-group.com/mail", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sf.ahtutils.xml.mail;
